dist: trusty
sudo: false

language: go
go_import_path: github.com/huaweicloud/huaweicloud-service-broker

go:
  - 1.x

install:
  - go build

script:
  - go fmt $(go list ./... | grep -v vendor)
  - go vet $(go list ./... | grep -v vendor)
  - go test $(go list ./... | grep -v vendor)

